export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_STATE_HOME="$HOME/.local/state"
export XDG_RUNTIME_DIR="/tmp/"

export TERM="xterm-256color"

# XDG DIR Config
export ASDF_DATA_DIR="${XDG_DATA_HOME}/asdf"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
export _Z_DATA="$XDG_DATA_HOME/z"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export NVM_DIR="$XDG_CONFIG_HOME/nvm/.nvm"
export YARN_CONFIG_HOME="$XDG_CONFIG_HOME/yarn/config"


export _JAVA_OPTIONS=-Djava.util.prefs.userRoot="$XDG_CONFIG_HOME/java"
export ASDF_CONFIG_FILE="${XDG_CONFIG_HOME}/asdf/asdfrc"
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
export CARGO_HOME="$XDG_CONFIG_HOME/cargo"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export IPYTHONDIR="$XDG_CONFIG_HOME/ipython"
export VSCODE_EXTENSIONS="/Applications/code-portable-data/extensions"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ZSH="$XDG_CONFIG_HOME/zsh/oh-my-zsh"
export ZDOTDIR="$XDG_CONFIG_HOME/zsh"

. $ASDF_DATA_DIR/plugins/java/set-java-home.zsh
