XDG_CONFIG_HOME="$HOME/.config"
XDG_CACHE_HOME="$HOME/.cache"
XDG_DATA_HOME="$HOME/.local/share"
XDG_STATE_HOME="$HOME/.local/state"
XDG_RUNTIME_DIR="/tmp/"

# Path to oh-my-zsh installation.
ZSH="$XDG_CONFIG_HOME/zsh/oh-my-zsh"
TERM="xterm-256color"

# XDG DIR Config
INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
CARGO_HOME="$XDG_CONFIG_HOME/cargo"
NVM_DIR="$XDG_CONFIG_HOME/nvm"
PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
_Z_DATA="$XDG_DATA_HOME/z"

export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export MACHINE_STORAGE_PATH="$XDG_DATA_HOME/docker-machine"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME/aws/credentials"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME/aws/config"
export VSCODE_EXTENSIONS="${XDG_DATA_HOME:-~/.local/share}/vscode/extensions"

# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
