caffeinate -i $XDG_CONFIG_HOME/zsh/install.sh
stty discard undef
ZSH_DISABLE_COMPFIX=true

# Path to oh-my-zsh installation.
export ZSH="$XDG_CONFIG_HOME/zsh/oh-my-zsh"
export TERM="xterm-256color"

# Options
# setopt hist_ignore_dups
# setopt hist_expire_dups_first

# General
DISABLE_AUTO_UPDATE="true"
DISABLE_AUTO_TITLE="false"
ENABLE_CORRECTION="false"
COMPLETION_WAITING_DOTS="true"
SAVEHIST=99999

# Comand exec time stamp in history file
HIST_STAMP="yyyy-mm-dd"

# Plugins
ZSH_CUSTOM="$XDG_CONFIG_HOME/zsh/custom"
plugins=(
    asdf
    alias-tips
    dirhistory
    fancy-ctrl-z
    git
    macos
    poetry
    z
    zsh-autosuggestions
    zsh-navigation-tools
    zsh-syntax-highlighting #must be last
)

# Theme
ZSH_THEME="agnoster-custom"

source $ZSH/oh-my-zsh.sh
source $XDG_CONFIG_HOME/dotfiles/_shellconfig/aliases
source $ZSH_CUSTOM/plugins/iterm2/.iterm2_shell_integration.zsh


# Added /include CFLAGS so XCode is working properly
export CFLAGS="$CFLAGS -I$(xcrun --show-sdk-path)/usr/include"
export EDITOR=vim
export FZF_DEFAULT_COMMAND='ag --hidden --ignore .git -g ""'
export GREP_COLOR="1;32"
export ZSH_PLUGINS_ALIAS_TIPS_TEXT="Alias: "
export PATH=$HOME/.gem/ruby/2.6.0/bin:$PATH
export PATH=$HOME/.node_modules/bin:$PATH
export PATH=$HOME/Applications/bin:$PATH
export PATH=$XDG_CONFIG_HOME/flutter/flutter/bin:$PATH
export PATH="/usr/local/opt/openjdk/bin:$PATH"
export PATH="$XDG_DATA_HOME/asdf/installs/rust/1.59.0/bin:$PATH"
export PATH="$XDG_CONFIG_HOME/poetry/bin:$PATH"  # poetry
# export PATH="/opt/homebrew/opt/python@3.8/bin:$PATH"
# export PATH="/opt/homebrew/opt/python@3.9/bin:$PATH"
export ANDROID_HOME=/usr/local/share/android-sdk

# python
export PYTHONDONTWRITEBYTECODE=1
export PYTHONUNBUFFERED=1
export VIRTUAL_ENV_DISABLE_PROMPT=1


# asdf
macos_version=$(sw_vers | grep "ProductVersion" | sed -e 's/ProductVersion://g' | xargs)
# if [[ "$OSTYPE" == "darwin"* ]]; then
#     if [[$macos_version]]; then
#     else
#     fi
#     echo "Detected Mac OSX system. Continuing with macconfig..."
#     ./_macconfig/main.sh
# else
#     echo "Continuing with linux/unix steps..."
#     ./_unixconfig/main.sh
# fi

. /opt/homebrew/opt/asdf/libexec/asdf.sh  # macos 12.3
. /usr/local/opt/asdf/libexec/asdf.sh # macos <12.3


# TheFuck
eval $(thefuck --alias)

if [[ -o login ]]; then
    export PATH="/Applications/Visual Studio Code.app/Contents/Resources/app/bin:$PATH"
fi
