
XDG_CONFIG_HOME="$HOME/.config"

# Path to oh-my-zsh installation.
ZSH="$XDG_CONFIG_HOME/zsh/oh-my-zsh"
TERM="xterm-256color"

# XDG DIR Config
INPUTRC="$XDG_CONFIG_HOME/readline/inputrc"
ZDOTDIR="$XDG_CONFIG_HOME/zsh"
CARGO_HOME="$XDG_CONFIG_HOME/cargo"
DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
NVM_DIR="$XDG_CONFIG_HOME/nvm"
NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"


# NVM
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
